# Generated by Django 2.2.7 on 2019-11-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispDeposit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonData',
        ),
    ]
