# Generated by Django 2.2.7 on 2019-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stkOut', models.PositiveIntegerField()),
                ('dbplay', models.PositiveIntegerField()),
                ('homerun', models.PositiveIntegerField()),
                ('balk', models.PositiveIntegerField()),
                ('wildPitch', models.PositiveIntegerField()),
                ('mistake', models.PositiveIntegerField()),
            ],
        ),
    ]
