# Generated by Django 2.2.7 on 2019-11-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_total_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totaldata',
            old_name='mistake',
            new_name='error',
        ),
        migrations.RenameField(
            model_name='totaldata',
            old_name='wildPitch',
            new_name='passedBall',
        ),
    ]
