# Generated by Django 2.2.7 on 2019-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_total_data', '0002_auto_20191125_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaldata',
            name='totalMoney',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
