# Generated by Django 2.2.7 on 2019-11-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_total_data', '0003_totaldata_totalmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totaldata',
            name='totalMoney',
        ),
    ]
