# Generated by Django 2.2.7 on 2019-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_total_data', '0004_remove_totaldata_totalmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaldata',
            name='money',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
